### ISSUE TITLE
chore: get open ssf certification

### ISSUE THREAD

**Issue by ayoayco** [astro-reactive/astro-reactive#102]
https://bestpractices.coreinfrastructure.org/en

**Comment by munyanezaarmel** [comment]
@ayoayco if this issue is still going on you can assign it to me

**Comment by ayoayco** [comment]
Sure @munyanezaarmel you can start in their checklist. Let me know if something needs my help.

**Comment by ayoayco** [comment]
Nope 😅 I think we're not ready for this...

**Comment by munyanezaarmel** [comment]
@ayoayco there are some checklists that require more explanations I think this should be self-assigned

**Comment by ayoayco** [comment]
Okay got it. Thanks for looking into it! @munyanezaarmel
