### ISSUE TITLE
chore: automate version management and package release

### ISSUE THREAD

**Issue by ayoayco** [astro-reactive/astro-reactive#225]
Explore semantic release bot for automated versioning and release

https://github.com/semantic-release/semantic-release

**Comment by fazzaamiarso** [comment]
@ayoayco I think we should consider `changeset` too. It's also recommended in turborepo docs. 

Here is a reference [https://github.com/changesets/changesets/blob/main/docs/decisions.md](https://github.com/changesets/changesets/blob/main/docs/decisions.md)

**Comment by ayoayco** [comment]
We have RELEASE.md files in each package, though they are manually updated by me each release.

Do you think those are a good start for changesets? @fazzaamiarso

**Comment by fazzaamiarso** [comment]
With Changesets I think it's a good starting point. We can also tweaks the changelog manually. Must look into it more to be sure.

Will get back to you later.
