### ISSUE TITLE
chore: investigate npm dependency issues

### ISSUE THREAD

**Issue by ayoayco** [astro-reactive/astro-reactive#242]
Doing a clean install for a new project from scratch by running `npm i @astro-reactive/form`, then checking the downloaded packages, I see that the installed versions are not the latest:

Our latest versions are `form@0.6.6,` `validator@0.2.6`, `common@0.1.4`

But the installed versions are validator@0.2.4 and common@0.1.3.

Goal for this issue is to figure out how we can make sure users will get the latest versions? Maybe we need to update our docs' instructions?

![Screenshot 2023-01-02 at 6 04 08 PM](https://user-images.githubusercontent.com/4262489/210261215-eee9c08b-05e3-4ca5-8fe1-7cf22a65f278.png)
![Screenshot 2023-01-02 at 6 04 00 PM](https://user-images.githubusercontent.com/4262489/210261217-1b024e18-b18c-4ed2-b89e-d751566c4a22.png)

**Comment by Preet-Sojitra** [comment]
I can give try on this

**Comment by ayoayco** [comment]
Thanks, @Preet-Sojitra! Let us know what you find!

**Comment by ayoayco** [comment]
cc @fazzaamiarso since you are also working on some release management task, maybe you have an idea? Let's work on this one together

**Comment by ayoayco** [comment]
Let me know if it will help if you also join the NPM organization

**Comment by fazzaamiarso** [comment]
@ayoayco we can work together. Will investigate tomorrow.

**Comment by fazzaamiarso** [comment]
@ayoayco for this issue, did you do the installation before #241 merged?

I've done the installation on fresh app today and get the latest version for all them.

**Comment by ayoayco** [comment]
@fazzaamiarso That's good to know! I did it after, but maybe I did it too soon and npm registry changes was not yet propagated. I will test again.

**Comment by Preet-Sojitra** [comment]
@ayoayco I also installed fresh app and checked the version. Versions of all the packages are up to Date as mentioned by @fazzaamiarso also. 
So we can close this issue.

**Comment by ayoayco** [comment]
Alright! Confirmed as well. Let's take note of this, npm needs time to propagate versions before we can test manually. Thanks @fazzaamiarso @Preet-Sojitra 🙏
