### ISSUE TITLE
chore(docs, landing-page): update links to repo

### ISSUE THREAD

**Issue by ayoayco** [astro-reactive/astro-reactive#244]
We moved! Now the links need updating 😅

✨ Find and update links to the repository in our docs and landing-page apps

**Comment by maddy020** [comment]
Hey @ayoayco 
I would like to work over this issue 
Please elaborate what changes are needed

**Comment by ayoayco** [comment]
The project repository has a new URL.

Search the codebase for the old URL "github.com/ayoayco/astro-reactive-library" and replace all with the new one:

github.com/astro-reactive/astro-reactive
