### ISSUE TITLE
feat: sharing configuration files with internal packages 

### ISSUE THREAD

**Issue by fazzaamiarso** [astro-reactive/astro-reactive#252]
Currently, configuration files (tsconfig, eslintrc) are independent to each packages, although they are the same. It's problematic when we want to create new packages, since it's tedious to write the config. 

So, our repo would have two new packages
```bash
packages
|-- eslint-config-custom
|-- tsconfig
```

We can create a package for sharing config files, as per turborepo docs recommendation to share files easier.
- [eslint package](https://turbo.build/repo/docs/handbook/linting/eslint)
- [tsconfig packages](https://turbo.build/repo/docs/handbook/linting/typescript)

**Comment by fazzaamiarso** [comment]
@ayoayco I think I will work on this issue first because I want to create new package for schema builder integrations, but found it tedious to create new config from scratch.

What do you think?

**Comment by ayoayco** [comment]
Aren't we using packages/common for this?

**Comment by fazzaamiarso** [comment]
In my opinion, `common` makes sense for files such as `form-control.types`, but not configs.

> EDIT: Ah but maybe you have something better in mind, do you mean putting the configuration under /packages?

I mean creating entirely new packages like [https://turbo.build/repo/docs/handbook/linting/eslint](https://turbo.build/repo/docs/handbook/linting/eslint). Since later we can add more custom config easily for packages with different technologies.  We can share it as dependencies.

**Comment by ayoayco** [comment]
> In my opinion, `common` makes sense for files such as `form-control.types`, but not configs.

Agreed, it was a crude solution to use `common` for configs, I think from before we migrated to turbo repo

> I mean creating entirely new packages like https://turbo.build/repo/docs/handbook/linting/eslint. Since later we can add more custom config easily for packages with different technologies. We can share it as dependencies.

Okay got it. Excited for this, go for it! Another question for my understaning, the docs you linked only discussed eslint configurations, but will it be as straightforward for tsconfig as well?

**Comment by fazzaamiarso** [comment]
Whoops! missed the tsconfig. Here you go [https://turbo.build/repo/docs/handbook/linting/typescript](https://turbo.build/repo/docs/handbook/linting/typescript).

tsconfig is more straightforward since they don't need any dependecies.

Oh, and better yet. Instead of in `/packages`, how about we create a new `/config`? It's not necessary to publish and version the config anyways.

**Comment by fazzaamiarso** [comment]
> I think this will also make it easier to solve https://github.com/astro-reactive/astro-reactive/issues/235

Definitely! 👍

**Comment by ayoayco** [comment]
> Instead of in `/packages`, how about we create a new `/config`? It's not necessary to publish and version the config anyways.

Yess this makes sense!
